name: Basic

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Show python version
        run: |
          python -V
          pip -V

      - name: Install python dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install --requirement requirements.txt

      - name: Run test
        run: pytest basic.py
