name: Context

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

env:
  GREETING: "Hello, World!"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "${GITHUB_CONTEXT}"

      - name: Env context
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "${ENV_CONTEXT}"

      - name: Job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "${JOB_CONTEXT}"

      - name: Runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "${RUNNER_CONTEXT}"
