name: Context

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: GitHub context
        run: echo "${{ toJson(github) }}"

      - name: Env context
        run: echo "${{ toJson(env) }}"
        env:
          GREETING: "Hello, World!"

      - name: Job context
        run: echo "${{ toJson(job) }}"

      - name: Runner context
        run: echo "${{ toJson(runner) }}"
