name: GitHub Script

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Return string
        id: return-result
        uses: actions/github-script@v7
        with:
          result-encoding: string # Choices: string, json (Default: json)
          script: return "Hello, World!"

      - name: Get string
        run: echo '${{ steps.return-result.outputs.result }}'

      - name: Show the first 10 fibonacci numbers
        uses: actions/github-script@v7
        with:
          script: |
            function fibonacci(n) {
              if (n <= 1) return n;
              return fibonacci(n - 1) + fibonacci(n - 2);
            }
            for (let i = 0; i < 10; i++) {
              console.log(fibonacci(i));
            }

      - name: Show context attributes
        uses: actions/github-script@v7
        with:
          script: |
            console.log(`Repository: ${JSON.stringify(context.repo)}`);
            console.log(`Event name: ${context.eventName}`);
            console.log(`SHA: ${context.sha}`);
            console.log(`Ref: ${context.ref}`);
            console.log(`Actor: ${context.actor}`);
