name: Homebrew

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check brew
        run: which brew || echo "Program not found"

      - name: Check fortune
        run: which fortune || echo "Program not found"

      - name: Setup homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install fortune
        run: brew install fortune

      - name: Run fortune
        run: |
          which fortune
          fortune
