name: Log Message

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest

    steps:
      - name: Notice message
        run: echo '::notice ::Notice me!'

      - name: Warning message
        run: echo '::warning ::Heed this warning.'

      - name: Error message
        run: echo '::error ::Error here.'
