name: Parallel

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

jobs:
  collect:
    name: Collect
    runs-on: ubuntu-latest
    outputs:
      TEST_DIRS: "${{ steps.generate.outputs.TEST_DIRS }}"

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install python dependencies
        run: |
          uv python install; echo
          uv sync --locked; echo
          uv tree

      - name: Collect tests
        run: |
          uv run -- pytest --collect-only --quiet | tee collected.tmp
          echo '::group::Delete the last two lines'
          sed -e '$d' collected.tmp | sed -e '$d' | tee collected.txt
          echo '::endgroup::'

      - name: Generate matrix
        id: generate
        shell: uv run -- python {0}
        run: |
          from pathlib import Path
          from os import environ
          test_dirs = set()
          with open("collected.txt", encoding="utf-8") as lines:
            for line in lines:
              parts = line.strip().partition("::")
              test_dirs.add(str(Path(parts[0]).parent))
          test_dirs = { "test_dirs": sorted(list(test_dirs)) }
          print(test_dirs)
          with open(environ["GITHUB_OUTPUT"], "a", encoding="utf-8") as f:
            print(f"TEST_DIRS={test_dirs}", file=f)

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: collect

    strategy:
      matrix:
        test_dirs: ${{ fromJSON(needs.collect.outputs.TEST_DIRS) }}
        # test_dir: ["tests", "tests/dir1", "tests/dir2", "tests/dir3"]

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install python dependencies
        run: |
          uv python install; echo
          uv sync --locked; echo
          uv tree

      - name: Run test
        run: uv run -- pytest '${{ matrix.test_dirs }}'

      - run: echo "TEST_DIRS is '${{ needs.collect.outputs.TEST_DIRS }}'"
