name: uv

on:
  push:
  schedule:
    - cron: "0 0 1 * *" # Midnight every month (UTC)
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Install python dependencies
        run: |
          uv python install; echo
          uv sync --locked; echo
          uv tree

      - name: Python shell with uv
        shell: uv run -- python {0}
        run: |
          import sys
          print(f"Running: {sys.version}")
          print("Hello, World!")

      - name: Run test
        run: uv run -- pytest tests/test_basic.py
